### PR TITLE
Fix parsing of envvars in MCA files

### LINKED ISSUE #1375: MCA parameter file parsing of env vars is broken
Specifying environment variables using the:

-x FOO=bar

syntax in MCA files is currently broken in master and v2.x. Specifying a line like above can lead to memory corruption, incorrect behavior, or just cause mpirun to abort.

I have opened #1374 to fix the issue on master but it will also need to be fixed on 2.x.

### PR DESCRIPTION
**Pull request by hjelmn**
This commit fixes a memory corruption bug when parsing lines of the
form:

-x FOO=bar

The code was making changes to the size of the buffer allocated for
key_buffer without making the appropriate changes to
key_buffer_len. This was causing subsequent calls to save_param_name
to write to invalid memory.

This commit makes the following changes:
- Fix the above bug by modifying trim_name to move the string within
  the buffer instead of re-allocating space for the trimmed string.
- Cleaned up both trim_name and save_param_name. Both functions took
  a prefix and suffix to trim. Problem was the prefix was not
  treated like a prefix. Instead the "prefix" was located inside the
  string using strstr then the trimmed value started after the
  substring (even in the middle of the string). To allow trimming
  both -x and --x (as well as -mca and --mca) trim_name is now
  called with each prefix.

Signed-off-by: Nathan Hjelm hjelmn@lanl.gov

(cherry picked from commit open-mpi/ompi@32236736a4ece4056d849f65e715242d85b86c4e)

Fixes open-mpi/ompi#1375

Signed-off-by: Nathan Hjelm hjelmn@me.com

### CODE REVIEW

**Comment by hjelmn** [comment]
:bot:label:bug
:bot:milestone:v2.0.0
:bot:assign: @jsquyres

@hppritcha If this is too much for v2.0.0 please go ahead and bump to v2.0.1. This is a new feature in v2.x and it is currently broken.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1349/ for details.

**Comment by hjelmn** [comment]
Should probably mention that all Mellanox Jenkins tests should be failing without this. I ran their Jenkins script on a TLCC2 system and the -tune tests abort due to memory corruption. Valgrind identified the exact source of the error.

File: opal/util/keyval_parse.c [hunk 1]
```diff
@@ -200,53 +201,58 @@ int opal_util_keyval_save_internal_envars(opal_keyval_parse_fn_t callback)
...
+        size_t prefix_len = strlen (prefix);
+
+        if (0 == strncmp (buffer, prefix, prefix_len)) {
+            pchr += prefix_len;
         }
     }
+
     /* trim spaces at the beginning */
-    while (' ' == *pchr || '\t' == *pchr) {
+    while (isspace (*pchr)) {
```
Comment (jsquyres) [inline opal/util/keyval_parse.c:225]: I realize that this is the way it was before you fixed it -- but shouldn't the prefix check come _after_ the beginning-of-string white space trim?

I ask because the suffix check comes _after_ the end-of-string white space trim.

File: opal/util/keyval_parse.c [hunk 2]
```diff
@@ -200,53 +201,58 @@ int opal_util_keyval_save_internal_envars(opal_keyval_parse_fn_t callback)
...
         pchr++;
     }
+
     /* trim spaces at the end */
-    echr = *buffer+strlen(*buffer)-1;
-    while (' ' == *echr || '\t' == *echr || '\n' == *echr) {
+    echr = buffer + buffer_len - 1;
+    while (isspace (*echr)) {
```
Comment (jsquyres) [inline opal/util/keyval_parse.c]: Shouldn't there be a check here to ensure that you don't run past the beginning of the buffer?

**Comment by hppritcha** [comment]
works for me now with srun/alps/mpirun :+1:

**Comment by hppritcha** [comment]
sorry wrong PR.

File: opal/util/keyval_parse.c (hunk 2 above)
Comment (hjelmn) [inline opal/util/keyval_parse.c]: Ok, will fix that and update the PR.

**Comment by hppritcha** [comment]
removed the reviewed label since that was accidentally generated by my erroneous comment.

**Comment by hppritcha** [comment]
@hjelmn could you incorporate @jsquyres 's feedback so we can merge?

**Comment by hjelmn** [comment]
sure.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1406/ for details.

**Comment by jsquyres** [comment]
@hjelmn Squash into one commit, and we're good.

**Comment by jsquyres** [comment]
Oh, these are master commits -- so we can't squash.  Ok.

**Comment by jsquyres** [comment]
:+1:

**Comment by jsquyres** [comment]
@hppritcha Good to go

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1412/ for details.
